### ISSUE TITLE
which part of water column is detided when IWD is applying?

### ISSUE THREAD

**Issue by weizilu** [NOC-MSM/SE-NEMO#172]
I hope this finds you well. I've read your enhancement about IWD and it is really helpful. However, I still have questions.
Following Arbic et al. (2010), the bottom flow over the bottom 500 m of the water column is used to detide and applied IWD. After checking your code: 
un_detide(ji,jj) = r1_25 * sum(un_25(ji,jj,:)) * i_is_25hrs + ( 1 - i_is_25hrs ) * 0.0 !un_b(ji,jj)
vn_detide(ji,jj) = r1_25 * sum(vn_25(ji,jj,:)) * i_is_25hrs + ( 1 - i_is_25hrs ) * 0.0 !vn_b(ji,jj)
I wonder which which part of water column is detided when IWD is applying? Is it only the bottom (the last layer)? Or did I miss something?
I would be appreciate if you can give me more information.
Thanks a lot.

**Comment by chris-O-wilson** [comment]
Hi @weizilu,

Thanks for your interest.  It's the barotropic component of the velocity (depth-mean) that is de-tided in our present implementation, so we do not exactly mirror the approach of Arbic et al. (2010).   The drag term that uses this detided velocity component is then applied as a barotropic term in the momentum tendency. 

Jérôme Chanut has been working on an updated version that also considers the baroclinic components of the 3D velocity, but as far as I am aware that is still under development.

Best wishes,
Chris

**Comment by weizilu** [comment]
Thanks for your reply.
I' m still confused. Does that mean that the IWD is only implemented into 2D barotropic modeling? Or this model can achieve 3D barotropic modeling (which can divide several layers in vertical direction), and applying IWD on depth-average flows?
Thanks a lot and best regards!
Zilu

**Comment by chris-O-wilson** [comment]
> Thanks for your reply. I' m still confused. Does that mean that the IWD is only implemented into 2D barotropic modeling? Or this model can achieve 3D barotropic modeling (which can divide several layers in vertical direction), and applying IWD on depth-average flows? Thanks a lot and best regards! Zilu

It's applied to the barotropic part of the barotropic-baroclinic mode splitting within the NEMO-ocean model.   If you want to apply this code to a model other than NEMO, it should be adapted and applied to the barotropic (depth-average) component of that model - which could be from similar mode-splitting or otherwise.    

Note that it is probably not correct to attempt to apply this to a shallow water model, as a key assumption this parameterisation is based on is a dimensional scaling for the energy flux between vertical modes of the tide (specifically, from mode-0 (barotropic) to mode-1 (1st baroclinic)).

Hope this helps to clarify things.
Best wishes,
Chris

**Comment by weizilu** [comment]
Thank you! I'm looking forward to your future work! It will be very helpful!
Actually, if you have published paper now, can you give me the title?
Thanks!

**Comment by chris-O-wilson** [comment]
Thanks @weizilu !    There is a paper in preparation, which we can share details of once published.   What is your email address please?

**Comment by weizilu** [comment]
Thanks a lot! My emial is jyweij@126.com.
